// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtU3R2ifShCOCXlZQZ4LlzbrPGKvJnP0M',
    appId: '1:817192435514:web:e879f6e021765ac2871a03',
    messagingSenderId: '817192435514',
    projectId: 'pineapple-talk-by-guri',
    authDomain: 'pineapple-talk-by-guri.firebaseapp.com',
    databaseURL: 'https://pineapple-talk-by-guri-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pineapple-talk-by-guri.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsIy7v-Ve7j7SlYFWlVJ3hjqs51N6k_Xc',
    appId: '1:817192435514:android:58e0f17590f00535871a03',
    messagingSenderId: '817192435514',
    projectId: 'pineapple-talk-by-guri',
    databaseURL: 'https://pineapple-talk-by-guri-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pineapple-talk-by-guri.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNiNw6Z3i6C35fW4k1EVYZAu-D2lMwLXs',
    appId: '1:817192435514:ios:88e2414adc1d6a1d871a03',
    messagingSenderId: '817192435514',
    projectId: 'pineapple-talk-by-guri',
    databaseURL: 'https://pineapple-talk-by-guri-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pineapple-talk-by-guri.appspot.com',
    iosClientId: '817192435514-son1er3r365a0pknionvtskuoq61ci52.apps.googleusercontent.com',
    iosBundleId: 'com.example.pineappleTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNiNw6Z3i6C35fW4k1EVYZAu-D2lMwLXs',
    appId: '1:817192435514:ios:88e2414adc1d6a1d871a03',
    messagingSenderId: '817192435514',
    projectId: 'pineapple-talk-by-guri',
    databaseURL: 'https://pineapple-talk-by-guri-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pineapple-talk-by-guri.appspot.com',
    iosClientId: '817192435514-son1er3r365a0pknionvtskuoq61ci52.apps.googleusercontent.com',
    iosBundleId: 'com.example.pineappleTalk',
  );
}
